# 1.
name: "Test & Build"

# 2.
on:
  pull_request:
    branches: [main,dev]
  push:
    branches: [dev]

# 3.
jobs:
  main:
    runs-on: ubuntu-latest

    # 4.
    steps:

      # 5.
      - name: Clone repository
        uses: actions/checkout@v4

      # 6.
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # better than zulu
          java-version: '17'       # 17 is standard now

      # 7.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      # 8.
      - name: Print Flutter version
        run: flutter --version

      # 9.
      - name: Get Flutter packages
        run: flutter pub get

      # 10.
      - name: Build APK
        run: flutter build apk

      # 11.
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
